Vagrant.configure("2") do |config|

  config.vm.provision "shell", inline: <<-SHELL
  dnf update -y
  dnf install -y vim curl wget net-tools
SHELL


  config.vm.define "gateway" do |gw|
    gw.vm.box = "generic/centos9s"
    gw.vm.hostname = "gateway"
    gw.vm.network "private_network", ip: "192.168.56.10"
  end

  config.vm.define "app" do |app|
    app.vm.box = "generic/centos9s"
    app.vm.hostname = "app"
    app.vm.network "private_network", ip: "192.168.56.11"
  end

  config.vm.define "client" do |client|
    client.vm.box = "generic/centos9s"
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.56.12"
  end

end
